"""drop abbreviation from person

Revision ID: 0ff4374fa3ad
Revises: f69d174071c2
Create Date: 2026-03-10 22:03:23.103204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff4374fa3ad'
down_revision = 'f69d174071c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('abbreviation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abbreviation', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
