"""add transport_mode to trip

Revision ID: 4821e7de2565
Revises: 0ff4374fa3ad
Create Date: 2026-03-11 09:37:23.615046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4821e7de2565'
down_revision = '0ff4374fa3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_mode', sa.String(length=20), nullable=False, server_default='flying'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('transport_mode')

    # ### end Alembic commands ###
