"""remove person color column

Revision ID: 4ea8301779a5
Revises: 635ee6612143
Create Date: 2026-03-14 22:39:35.829300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea8301779a5'
down_revision = '635ee6612143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=7), server_default=sa.text("'#3388ff'"), nullable=False))

    # ### end Alembic commands ###
