"""Add Person and trip_person tables

Revision ID: 6148dc84f216
Revises: dc623fd7b7a5
Create Date: 2026-02-27 13:52:07.156656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6148dc84f216'
down_revision = 'dc623fd7b7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_location_label', sa.String(length=200), nullable=False),
    sa.Column('default_location_lat', sa.Float(), nullable=False),
    sa.Column('default_location_lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trip_person',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('trip_id', 'person_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_person')
    op.drop_table('person')
    # ### end Alembic commands ###
