"""add notification_preferences to person

Revision ID: 635ee6612143
Revises: 4821e7de2565
Create Date: 2026-03-14 18:32:14.940582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635ee6612143'
down_revision = '4821e7de2565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_preferences', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('notification_preferences')

    # ### end Alembic commands ###
