"""Add email column to Person

Revision ID: 90875689ea8b
Revises: bb38d6034c11
Create Date: 2026-02-27 16:10:26.087703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90875689ea8b'
down_revision = 'bb38d6034c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=254), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
