"""Add Family model and Person.family_id, Person.color

Revision ID: bb38d6034c11
Revises: 6148dc84f216
Create Date: 2026-02-27 14:19:35.182211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb38d6034c11'
down_revision = '6148dc84f216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=False, server_default='#3388ff'))
        batch_op.create_foreign_key('fk_person_family_id', 'family', ['family_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint('fk_person_family_id', type_='foreignkey')
        batch_op.drop_column('color')
        batch_op.drop_column('family_id')

    op.drop_table('family')
    # ### end Alembic commands ###
