"""add trip_stop table

Revision ID: fef568fe36ae
Revises: a83b4236e7eb
Create Date: 2026-02-28 15:55:49.159635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef568fe36ae'
down_revision = 'a83b4236e7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_person_flight', schema=None) as batch_op:
        batch_op.alter_column('outbound_flight',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('return_flight',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###

    # Data migration: create a TripStop for each existing Trip
    conn = op.get_bind()
    trips = conn.execute(sa.text(
        "SELECT id, destination, latitude, longitude, start_date, end_date FROM trip"
    ))
    for trip in trips:
        conn.execute(sa.text(
            "INSERT INTO trip_stop (trip_id, \"order\", destination, latitude, longitude, start_date, end_date) "
            "VALUES (:trip_id, 0, :destination, :latitude, :longitude, :start_date, :end_date)"
        ), {
            "trip_id": trip.id,
            "destination": trip.destination,
            "latitude": trip.latitude,
            "longitude": trip.longitude,
            "start_date": trip.start_date,
            "end_date": trip.end_date,
        })


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_person_flight', schema=None) as batch_op:
        batch_op.alter_column('return_flight',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('outbound_flight',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    op.drop_table('trip_stop')
    # ### end Alembic commands ###
